import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import localFont from "next/font/local";
import Navbar from "@/components/Navbar";
import ParticlesBackground from "@/components/ui/ParticlesBackground";
import Footer from "@/components/Footer";

export const secondaryFont = localFont({
  src: "../public/fonts/Philosopher-Regular.ttf",
});

export const mainFont = Poppins({
  weight: ["400"],
});

// TODO:
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// TODO:

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth selection:bg-secondary-color">
      <body
        className={`bg-primary-color text-sm sm:text-base ${mainFont.className} text-stone-50 antialiased`}
      >
        <ParticlesBackground />
        <Navbar />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
