import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import localFont from "next/font/local";
import { Poppins } from "next/font/google";
import ParticlesBackground from "@/components/ui/ParticlesBackground";

export const mainFont = localFont({
  src: "../public/fonts/Philosopher-Regular.ttf",
});

export const secondaryFont = Poppins({
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`bg-primary-color ${secondaryFont.className} text-stone-50 antialiased`}
      >
        <ParticlesBackground />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
