import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import ParticlesBackground from "@/components/ui/ParticlesBackground";
import { mainFont } from "@/public/fonts/fonts";

// TODO:
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// TODO:

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth selection:bg-secondary-color">
      <body
        className={`bg-primary-color text-sm sm:text-base w-full ${mainFont.className} text-stone-50 antialiased`}
      >
        <ParticlesBackground />
        <Navbar />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
